config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resources :categories
    resources :places
    devise_for :users, skip: :omniauth_callbacks, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }
    resources :categories

    root 'static_pages#index'
    devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end

    get 'articles/pdf/:id', to: 'articles#pdf', as: 'article_pdf'

    resources :articles do
      resources :comments
      collection do
        match 'search' => 'articles#search', via: [:get, :post], as: :search
      end
    end
    resources :users do
      resources :phones
    end
    resources :likes, only: %i[create destroy]
    resources :dislikes, only: %i[create destroy]
    get '/languages/:language', to: 'language#show', as: 'languages'
    get '/members_only/articles', to: 'members#articles', as: 'members_only_articles'
    get '/:id/locations', to: 'users#locations', as: 'user_locations'
    get '/explore', to: 'articles#explore', as: 'explore_articles'

    scope controller: :static do
      get :pricing
    end
    get '/success', to: 'purchase/checkouts#success'

    namespace :purchase do
      resources :checkouts
    end

    resources :subscriptions

    scope 'admin' do
      delete 'users/:id', to: 'admin#user_destroy', via: 'delete', as: 'admin_destroy_user'
      get ':id', to: 'admin#show', as: 'admin'
      get 'change_role/:id', to: 'admin#change_role', as: 'admin_change_role'
      patch 'make_admin/:id', to: 'admin#make_admin', via: 'patch', as: 'admin_make_admin'
      patch 'make_user/:id', to: 'admin#make_user', via: 'patch', as: 'admin_make_user'
      patch 'make_member/:id', to: 'admin#make_member', via: 'patch', as: 'admin_make_member'

      get 'article/approve/:id', to: 'admin#article_approve',  as: 'admin_article_approve'
      get 'article/disapprove/:id', to: 'admin#article_disapprove', as: 'admin_article_disapprove'
    end
  end
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  include Visible
  belongs_to :user
  has_rich_text :body
  has_one :approver
  has_many :article_categories, dependent: :destroy
  has_many :categories, through: :article_categories
  accepts_nested_attributes_for :categories, allow_destroy: true, reject_if: lambda { |attributes|
                                                                               attributes[:name].blank?
                                                                             }
  validates_associated :categories
  has_noticed_notifications model_name: 'Notification'
  has_many :notifications, through: :user, dependent: :destroy

  def set_default_approver
    self.approver ||= nil
  end

  enum language: %i[english georgian]
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :dislikes, as: :dislikeable, dependent: :destroy
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  include ActiveModel::Dirty
  before_action :set_article, only: %i[update]
  before_action :check_if_changed, only: %i[update]

  def index
    @q = Article.ransack(params[:q])
    @articles = @q.result.paginate(page: params[:page], per_page: 10)
    @category = Category.all
  end

  def search
    @articles = Article.where('title_or_descriprion LIKE ?', "%#{params[:q]}%").paginate(page: params[:page],
                                                                                         per_page: 10)
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments.order('created_at DESC').paginate(page: params[:page], per_page: 3)
    @comment = Comment.new
    mark_notifications_as_read
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: [@article.id, @article.title].join('-'),
        template: "articles/article",
        formats: [:html],
        disposition: :inline,
        layout: 'pdf'
      end
    end
  end



  def new
    @categories = Category.all
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def explore
    @articles = Article.all.shuffle
  end

  def edit
    @article = Article.find(params[:id])
    @categories = Category.all
  end

  def update
    @user = @article.user
    @article.approved_will_change!
    # binding.irb

    SendEmailJob.perform_now(@article) if @current_value == true && check_if_changed == true
    if @article.update(article_params)
      # binding.irb
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
      format.js   { render layout: false }
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :status, :language, :approved, :description, :body,
                                    categories_attributes: %i[name destroy], category_ids: [])
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def check_if_changed
    @current_value = params.require(:article)[:approved]
    @current_value = true if params.require(:article)[:approved] == '1'
    @current_value = false if params.require(:article)[:approved] == '0'
    @article.approved != @current_value
  end

  def mark_notifications_as_read
    if current_user
      notifications_to_mark_as_read = @article.notifications_as_article.where(recipient: current_user)
      notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
    end
  end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
  require 'rubygems'
  require 'htmlentities'

# Support functions for Premailer
module HtmlToPlainText

  # Returns the text in UTF-8 format with all HTML tags removed
  #
  # TODO: add support for DL, OL
  def convert_to_text(html, line_length = 65, from_charset = 'UTF-8')
    txt = html

    # strip text ignored html. Useful for removing
    # headers and footers that aren't needed in the
    # text version
    txt.gsub!(/<!-- start text\/html -->.*?<!-- end text\/html -->/m, '')

    # replace images with their alt attributes
    # for img tags with "" for attribute quotes
    # with or without closing tag
    # eg. the following formats:
    # <img alt="" />
    # <img alt="">
    txt.gsub!(/<img.+?alt=\"([^\"]*)\"[^>]*\>/i, '\1')

    # for img tags with '' for attribute quotes
    # with or without closing tag
    # eg. the following formats:
    # <img alt='' />
    # <img alt=''>
    txt.gsub!(/<img.+?alt=\'([^\']*)\'[^>]*\>/i, '\1')

    # links
    txt.gsub!(/<a\s.*?href=["'](mailto:)?([^"']*)["'][^>]*>((.|\s)*?)<\/a>/i) do |s|
      if $3.empty?
        ''
      else
        $3.strip + ' ( ' + $2.strip + ' )'
      end
    end

    # handle headings (H1-H6)
    txt.gsub!(/(<\/h[1-6]>)/i, "\n\\1") # move closing tags to new lines
    txt.gsub!(/[\s]*<h([1-6]+)[^>]*>[\s]*(.*)[\s]*<\/h[1-6]+>/i) do |s|
      hlevel = $1.to_i

      htext = $2
      htext.gsub!(/<br[\s]*\/?>/i, "\n") # handle <br>s
      htext.gsub!(/<\/?[^>]*>/i, '') # strip tags

      # determine maximum line length
      hlength = 0
      htext.each_line { |l| llength = l.strip.length; hlength = llength if llength > hlength }
      hlength = line_length if hlength > line_length

      case hlevel
        when 1   # H1, asterisks above and below
          htext = ('*' * hlength) + "\n" + htext + "\n" + ('*' * hlength)
        when 2   # H1, dashes above and below
          htext = ('-' * hlength) + "\n" + htext + "\n" + ('-' * hlength)
        else     # H3-H6, dashes below
          htext = htext + "\n" + ('-' * hlength)
      end

      "\n\n" + htext + "\n\n"
    end

    # wrap spans
    txt.gsub!(/(<\/span>)[\s]+(<span)/mi, '\1 \2')

    # lists -- TODO: should handle ordered lists
    txt.gsub!(/[\s]*(<li[^>]*>)[\s]*/i, '* ')
    # list not followed by a newline
    txt.gsub!(/<\/li>[\s]*(?![\n])/i, "\n")

    # paragraphs and line breaks
    txt.gsub!(/<\/p>/i, "\n\n")
    txt.gsub!(/<br[\/ ]*>/i, "\n")

    # strip remaining tags
    txt.gsub!(/<\/?[^>]*>/, '')

    # decode HTML entities
    he = HTMLEntities.new
    txt = he.decode(txt)

    # no more than two consecutive spaces
    txt.gsub!(/ {2,}/, " ")

    txt = word_wrap(txt, line_length)

    # remove linefeeds (\r\n and \r -> \n)
    txt.gsub!(/\r\n?/, "\n")

    # strip extra spaces
    txt.gsub!(/[ \t]*\302\240+[ \t]*/, " ") # non-breaking spaces -> spaces
    txt.gsub!(/\n[ \t]+/, "\n") # space at start of lines
    txt.gsub!(/[ \t]+\n/, "\n") # space at end of lines

    # no more than two consecutive newlines
    txt.gsub!(/[\n]{3,}/, "\n\n")

    # the word messes up the parens
    txt.gsub!(/\(([ \n])(http[^)]+)([\n ])\)/) do |s|
      ($1 == "\n" ? $1 : '' ) + '( ' + $2 + ' )' + ($3 == "\n" ? $1 : '' )
    end

    txt.strip
  end

  # Taken from Rails' word_wrap helper (http://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-word_wrap)
  def word_wrap(txt, line_length)
    txt.split("\n").collect do |line|
      line.length > line_length ? line.gsub(/(.{1,#{line_length}})(\s+|$)/, "\\1\n").strip : line
    end * "\n"
  end
end
end

app/views/articles/_articles.html.erb
<div class="digg_pagination center pagination justify-content-center">    
  <%= will_paginate @articles.where.not(status: 'members only') if @articles.count > 10%>
</div>

  <div class='general' >
    
    <table >
       <thead>
    <tr class = 'row'>
      <th scope="col"></th>
      </tr> 
      </thead>
      <% @articles.where.not(status: 'members only').each do |article| %>
    <% unless article.archived? || (article.private? || article.approved == false && article.user != current_user) %>    
      <tbody id="articles" style="margin-top:20px" >
      <tr>
        <td><span class='title'><%=article.title.capitalize%></span><br> </td> 
      </tr>
      <tr>
       <td><%= article.description || t("no description")%></td>
      </tr>

      <tr>
        <td> <%= t("category")%>: <% Category.where(id: article.category_ids).find_each do |category|%>
        <%= link_to category.name, category_path(category.id) %>   
        <%end%></td>
      </tr>

      <tr>
        <td> <%= t("by")%>: <%= link_to article.user.user_name, user_path(article.user), {:class => "btn btn-secondary"} %></td></tr>
        <td> <% if user_signed_in? && current_user == article.user %>
          <div>  
            <%= link_to t("Edit"), edit_article_path(article), {:class => "btn btn-outline-secondary"} %> 
            <%= link_to t("Destroy"), article_path(article), data: {
                              turbo_method: :delete,
                              turbo_confirm: t("Are you sure?")
                            }, style: 'color: black;', class: 'btn btn-outline-secondary' %>
          </div>
         <%end%>
        </td>
      </tr>
    </tbody> 

      <tr style="margin-bottom:20px; background-color:white">
      <td style="text-align:right"><%= button_to t("read more"), article_url(article), :method => :get, class:"btn btn-dark"%></td>      <tr >
      <tr>
  <% end %>

  <% end %> 
      </table>
    </div>
    <div class="digg_pagination center pagination justify-content-center">    
      <%= will_paginate @articles.where.not(status: 'members only')%>
    </div>

app/views/articles/_blogs.html.erb
<% @articles.each do |article| %>
    <% unless article.archived? || (article.private? && article.user != current_user) %>
      <table class='articles'>
        <td><%= link_to article.title, article %></td>
       </tr>
        <tr>
       <td><%= article.body.split(" ").first(30).join(" ")%></td>
      </tr>
     </table>
    <% end %>
    <% if user_signed_in? && current_user == article.user %>

<div class='blogeddit'>
  <%= link_to "Edit", edit_article_path(article) %> <%= link_to "Destroy", article_path(article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
                  </div>
<%end%>
  <% end %>
    <div class="digg_pagination center">
    
<%= will_paginate @articles%>
</div>

app/views/articles/_form.html.erb
<div class="article_form">
<%= form_with model: article do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= I18n.locale == :en ? pluralize(article.errors.count, "error") : "#{article.errors.count} შეცდომის გამო" %> <%= t("prohibited this article from being saved")%>:</h2>
      <ul>
        <% article.errors.each do |error| %>
          <li><%= t(error.full_message) %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div style='margin: 40px'>
    <%= form.label t(:title) %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div style='margin: 40px;'>
    <%= form.label t(:body) %><br>
    <%= form.rich_text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

    <div style='margin-left: 40px;'>
    <%= form.label t(:description) %><br>
    <%= form.text_area :description %>
    <% article.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

 
   <div class ='form-group' style='margin-left: 40px;'>
    <% if !@categories.nil? %>
      <%= form.label t(:categories) %>
      <%= form.collection_select :category_ids, Category.where("approved = ?", true).order(:name), :id, :name, {},
      {class: 'form-control select2', multiple:true}%>
    <% end %>
</div>

  <div style='margin-left: 40px;'>
    <%= form.label t(:status) %><br>
    <%= form.select :status, ['public', 'private', 'archived', 'members only'], selected:'public' %>
  </div>
      <br>
  <div style='margin-left: 40px;'>
    <h6><%= t("please choose a language of your article so that readers can find your article easier") %><h6>
    <%= form.label t(:language) %><br>
    <%= form.select :language, ['english', 'georgian'], selected:'english' %>
  </div>


<%if current_user.role == "admin"%>
  <%= form.check_box :approved %>
  <%= label_tag :approve, t("check to approve") %>
<%end%>
 <div style="text-align:center; margin-top: 100px">
    <%= form.submit :class => "btn btn-danger" %>
  </div>
<% end %>
</div>

app/views/articles/article.html.erb
<p class='author'> author : <%=  @article.user.email.split("@")[0] %> 
<p><%= @article.title %><p>
<p><%= @article.body %></p>

app/views/articles/edit.html.erb
<%= render "form", article: @article %>

app/views/articles/explore.html.erb
<div >
  <h2 style="text-align:center;
   margin: 30px; padding:30px;
   background-color:cornflowerblue;
   width:100%; box-shadow: 0 1px 6px rgba(0, 0, 0, 0.12), 0 1px 4px rgba(0, 0, 0, 0.24); 
   color:white;
   text-shadow: -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000;">
  <%= t("Too many atricles to choose which one to start with? explore random three articles and see what fate brings to you!")%>
  </h2>
  <br>
  <% filtered_articles = []%>
  <% @articles.each do |article| %>
    <% unless article.archived? ||(article.private? || article.approved == false && article.user != current_user) || article.status == 'members only' %> 
      <% filtered_articles << article %>
    <%end%>
  <%end%>

  <table >
        <thead>
      <tr class = 'row'>
        <th scope="col"></th>
        </tr> 
        </thead>  
  <% filtered_articles[0..2].each do |article| %>
        <tbody id="articles" style="margin: 30px;
  background-color: white;
  opacity: 0.6;
  padding: 30px">
        <tr >
          <td ><span class='title' style="font-size: 25px"><%=article.title.capitalize%></span><br> </td> 
        </tr>
        <tr>
        <td><%= article.description || t("no description")%></td>
        </tr>
      </tbody>
            <tr style="margin-bottom:20px; background-color:white">
          <td style="text-align:right"><%= button_to t("read more"), article_url(article), :method => :get, class:"btn btn"%></td>      <tr >
        <tr>
  <% end %>
  </table>
</div>

app/views/articles/index.html.erb
<div style="text-align:center; margin-top:20px">
  <%= search_form_for @q, remote: true do |f| %>
    <%= f.search_field :title_or_description_cont, placeholder: t('search for articles'), style: "text-align:center"  %>
    <%= f.submit :class => "btn btn-dark"%>
  <% end %>
</div>
<% if user_signed_in? && current_user.role == "admin" %>
  <%= render "partials/allarticles", articles: @articles%>
<%else%>
   <%=render partial: 'articles'%>
<%end%>


<body>
    <%= yield %>
</body>

app/views/articles/new.html.erb
<%= render "form", article: @article %>

app/views/articles/search.html.erb
<h1>search result</h1>
<%= render 'articles/articles', articles: @articles %>

app/views/articles/show.html.erb
<div class="article_show">
<h1><%= current_user == @article.user ||(current_user.role == 'admin' if user_signed_in?) ? (link_to @article.title, edit_article_path(@article)) :  @article.title %></h1>
<h6 style=" font-style: italic; "><%= @article.status%></h6>
<p><%= @article.body %></p>
<p class='author'> author : <%= link_to @article.user.email.split("@")[0], user_path(@article.user), {:class => "btn btn-outline-secondary"}
  %> 
</p>
<%if user_signed_in?%>
 <%= link_to t("get a PDF"), article_path(@article, format: :pdf), target: :_blank %>
 <br>
<%end%>
<div class="reactions"> 
  <p> likes:<%= @article.likes.count%> dislikes:<%= @article.dislikes.count%> <p>
<%if user_signed_in?%>
  <%like = current_user.likes.find_by(likeable: @article) %>
  <% if like.nil? %>
    <form action="/likes" method="post" style="display:inline">
      <input type ="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">
      <input type ="hidden" name="like[likeable_id]" value="<%= @article.id %>">
      <input type ="hidden" name="like[likeable_type]" value="Article">
      <button type ="submit" class= "btn">
        <i class="bi bi-heart"  style="font-size: 1.5em; color: grey; "></i>
      </button>

    </form>
  <%else%>
    <form action="<%= like_path(like)%>" method="post" style="display:inline">
      <input type ="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">
      <input type ="hidden" name="_method" value="DELETE">
      <button type ="submit" class= "btn">
      <i class="bi bi-heart-fill"  style="font-size: 1.5em; color: red; "></i>
      </button>    </form>
  <%end%>
<%end%>

<%if user_signed_in? %>
<% dislike = current_user.dislikes.find_by(dislikeable: @article) %>
  <% if dislike.nil? %>
    <form action="/dislikes" method="post" style="display:inline">
      <input type ="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">
      <input type ="hidden" name="dislike[dislikeable_id]" value="<%= @article.id %>">
      <input type ="hidden" name="dislike[dislikeable_type]" value="Article">
      <button type ="submit" class= "btn" >
        <i class="bi bi-heartbreak" style="font-size: 1.5em; color: grey; "></i>
      </button>
    </form>
    <%else%>
    <form action="<%= dislike_path(dislike)%>" method="post" style="display:inline">
      <input type ="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">
      <input type ="hidden" name="_method" value="DELETE">
      <button type ="submit" class= "btn" >
        <i class="bi bi-heartbreak-fill"  style="font-size: 1.5em; color: black; "></i>
      </button> 
     </form>  
  <%end%>
<%end%>
</div>
<br>
<div     style= "padding: 1em; margin: 1em;">

 <%if user_signed_in?%>
    <%= render 'comments/form', submit_tag: "comment", article: @article, comment: @article.comments.build %>
  <%end%>  

</div>
<% if @article.comments.count>0 %>
  <h5><%= t("comments")%> : </h5>
<div class="container">
  <% @comments.each do |comment| %>
    <%= render 'comments/comment', 
    article: @article, 
    comment: comment %>
  <% end %>
</div>  
  <div class="digg_pagination center">
    <%= will_paginate @comments%>
  </div>
<% end %>