config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resources :categories
    resources :places
    devise_for :users, skip: :omniauth_callbacks, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }
    resources :categories

    root 'static_pages#index'
    devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end

    get 'articles/pdf/:id', to: 'articles#pdf', as: 'article_pdf'

    resources :articles do
      resources :comments
      collection do
        match 'search' => 'articles#search', via: [:get, :post], as: :search
      end
    end
    resources :users do
      resources :phones
    end
    resources :likes, only: %i[create destroy]
    resources :dislikes, only: %i[create destroy]
    get '/languages/:language', to: 'language#show', as: 'languages'
    get '/members_only/articles', to: 'members#articles', as: 'members_only_articles'
    get '/:id/locations', to: 'users#locations', as: 'user_locations'
    get '/explore', to: 'articles#explore', as: 'explore_articles'

    scope controller: :static do
      get :pricing
    end
    get '/success', to: 'purchase/checkouts#success'

    namespace :purchase do
      resources :checkouts
    end

    resources :subscriptions

    scope 'admin' do
      delete 'users/:id', to: 'admin#user_destroy', via: 'delete', as: 'admin_destroy_user'
      get ':id', to: 'admin#show', as: 'admin'
      get 'change_role/:id', to: 'admin#change_role', as: 'admin_change_role'
      patch 'make_admin/:id', to: 'admin#make_admin', via: 'patch', as: 'admin_make_admin'
      patch 'make_user/:id', to: 'admin#make_user', via: 'patch', as: 'admin_make_user'
      patch 'make_member/:id', to: 'admin#make_member', via: 'patch', as: 'admin_make_member'

      get 'article/approve/:id', to: 'admin#article_approve',  as: 'admin_article_approve'
      get 'article/disapprove/:id', to: 'admin#article_disapprove', as: 'admin_article_disapprove'
    end
  end
end

app/models/approver.rb
# frozen_string_literal: true

class Approver < ApplicationRecord
  belongs_to :article
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  include Visible
  belongs_to :user
  has_rich_text :body
  has_one :approver
  has_many :article_categories, dependent: :destroy
  has_many :categories, through: :article_categories
  accepts_nested_attributes_for :categories, allow_destroy: true, reject_if: lambda { |attributes|
                                                                               attributes[:name].blank?
                                                                             }
  validates_associated :categories
  has_noticed_notifications model_name: 'Notification'
  has_many :notifications, through: :user, dependent: :destroy

  def set_default_approver
    self.approver ||= nil
  end

  enum language: %i[english georgian]
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :dislikes, as: :dislikeable, dependent: :destroy
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :article_categories, dependent: :destroy
  has_many :articles, through: :article_categories

  validates :name, uniqueness: true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  include Visible

  belongs_to :article
  belongs_to :user

  after_initialize :set_default_status, if: :new_record?
  after_create_commit :notify_recipient
  before_destroy :cleanup_notifications
  has_noticed_notifications model_name: 'Notification'

  def set_default_status
    self.status ||= 'public'
  end

  validates :body, presence: true

  private

  def notify_recipient
      CommentNotification.with(comment: self, article: article).deliver(article.user)
  end

  def cleanup_notifications
    notifications_as_comment.destroy_all
  end
end

app/models/dislike.rb
# frozen_string_literal: true

class Dislike < ApplicationRecord
  validates :user_id, uniqueness: { scope: %i[dislikeable_id dislikeable_type] }
  belongs_to :user
  belongs_to :dislikeable, polymorphic: true

  after_create_commit :notify_recipient
  before_destroy :cleanup_notifications
  has_noticed_notifications model_name: 'Notification'

  private

  def notify_recipient
      DislikeNotification.with(dislike: self, article: self.dislikeable).deliver(self.dislikeable.user)
  end

  def cleanup_notifications
    notifications_as_dislike.destroy_all
  end
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: %i[likeable_id likeable_type] }
  belongs_to :user
  belongs_to :likeable, polymorphic: true

  after_create_commit :notify_recipient
  before_destroy :cleanup_notifications
  has_noticed_notifications model_name: 'Notification'

  private

  def notify_recipient
      LikeNotification.with(like: self, article: self.likeable).deliver(self.likeable.user)
  end

  def cleanup_notifications
    notifications_as_like.destroy_all
  end
end

app/models/notification.rb
# frozen_string_literal: true

class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

app/models/phone.rb
# frozen_string_literal: true

class Phone < ApplicationRecord
  belongs_to :user
  validates :phone, presence: true, uniqueness: true
  validates :country, presence: true
  validate :valid_phone
  validates_format_of :phone, with: /\d[0-9]\)*\z/, message: 'Only positive number without spaces are allowed'

  def valid_phone
    errors.add(:phone, 'format not supported for chosen coutry') unless TelephoneNumber.parse(phone,
                                                                                              country).valid?
  end
end

app/models/place.rb
# frozen_string_literal: true

class Place < ApplicationRecord
  belongs_to :user
  reverse_geocoded_by :latitude, :longitude, address: :name
  after_validation :reverse_geocode
  validates :latitude, presence: true
  validates :longitude, presence: true
end

app/models/subscription.rb
# frozen_string_literal: true

class Subscription < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and
  enum role: %i[user member admin]
  mount_uploader :avatar, AvatarUploader

  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :user
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  devise :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy
  has_many :phones, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :places, dependent: :destroy
  has_many :notifications, as: :recipient, dependent: :destroy
  # User Avatar Validation
  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless user
      user = User.create(
        email: data['email'],
        user_name: data['email'].split('@').first.gsub(/[^0-9a-zA-Z]/i, '').downcase[0, 12],
        password: Devise.friendly_token[0, 20],
        confirmed_at: Time.now
      )
      # user.skip_confirmation!
      return { user: user, new_user: true }
    end
    { user: user, new_user: false }
  end
end

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
end

app/helpers/charges_helper.rb
# frozen_string_literal: true

module ChargesHelper
end

app/helpers/dilikes_helper.rb
# frozen_string_literal: true

module DilikesHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/members_helper.rb
# frozen_string_literal: true

module MembersHelper
end

app/helpers/phones_helper.rb
# frozen_string_literal: true

module PhonesHelper
end

app/helpers/places_helper.rb
# frozen_string_literal: true

module PlacesHelper
end

app/helpers/static_helper.rb
# frozen_string_literal: true

module StaticHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/edit.html.erb
<h1>Admin#edit</h1>
<p>Find me in app/views/admin/edit.html.erb</p>

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/admin/new.html.erb
<h1>Admin#new</h1>
<p>Find me in app/views/admin/new.html.erb</p>

app/views/admin/show.html.erb
<p> <%= t("email")%>: <%= @user.email%> </p>
<p><%= t("role")%>: <%= t("#{@user.role}") %></p>


  <%= link_to t("users"), users_path %>
  <%= link_to t("all articles"), articles_path %>

app/views/admin/update.html.erb
<h1>Admin#update</h1>
<p>Find me in app/views/admin/update.html.erb</p>

app/views/confirmables/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/confirmables/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/partials/_admin.html.erb
<p> email: <%= @user.email%> </p>
<p>role: <%= @user.role %></p>

<%= render 'articles/blogs', articles: @articles %>


  <%= link_to t("create new article"), new_article_path %>
  <%= link_to t("all articles"), articles_path %>
  <% if policy(User).index? %>
    <%= link_to t("#{users}"), users_path %>
  <%end %>

       

app/views/partials/_allarticles.html.erb
<table class="admintable table-bordered">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col"><%= sort_link(@q, :title, t("Title")) %></th>
      <th scope="col"><%= sort_link(@q, :description, t("description")) %></th>
      <th scope="col"><%= sort_link(@q, :language, t("language")) %></th>
      <th scope="col"><%= sort_link(@q, :created_at, t("created_at")) %></th>
      <th scope="col"><%= sort_link(@q, :status, t("status")) %></th>
      <th scope="col"><%= sort_link(@q, :user_name_or_email_or_role, t("author")) %></th>
      <th scope="col"><%= link_to t("category"), categories_path %></th>
      <th scope="col"><%= sort_link(@q, :approved, t("approved")) %></th> 
      <th scope="col"> </th>
      <th scope="col"> </th>
      <th scope="col"><%=  t("likes")%></th>
      <th scope="col"><%=  t("comments") %></th>
      </tr>
  </thead>  
  <tbody>

  <% @articles.each do |article| %>
    <tr>
      <th scope="row"><%= article.id %></th>
      <td><%= link_to article.title, article_path(article) %></td>
      <td><%= article.description || "no description" %></td>
      <td><%= article.language || "not chosen" %></td>
      <td><%= article.created_at %></td>
      <td><%= t("#{article.status}") %></td>
      <td><%= link_to article.user.email, user_path(article.user_id) %></td>
       <td><% Category.where(id: article.category_ids).find_each do |category|%> 
      <%= link_to t("#{category.name}"), category_path(category.id) %>   
      <%end%></td>   
      <td><%= article.approved ? t("approved") : t("not approved")%></td>
      <td><%= link_to t("Edit"), edit_article_path(article) %></td>
      <td><%= link_to t("Destroy"), article_path(article), data: {
                    turbo_method: :delete,
                    turbo_confirm: t("Are you sure?")
                  } %></td>
      <td><%= article.likes.count %></td>
      <td><%= article.comments.count %></td>


    </tr>
  
<% end %>
 </tbody>
   <div class="digg_pagination center article_index">    
  <%= will_paginate @articles if @articles.count > 10%>
</div>
</table>

app/views/partials/_articles.html.erb
    <li class="btn nav-item dropdown">
      <%= link_to t("articles"), articles_path, :class => 'nav-link text-light',:style=>"color:white;" %>
    </a>
    <ul class="dropdown-menu dropdown-menu-lg-end dropdown-content" aria-labelledby="navbarDropdown">
      <li class="dropdown-item">
        <%= link_to t("new article"),
          new_article_path, class:"nav-link text-dark" %>
      </li>

      <li class="dropdown-item">
        <%= link_to t("explore"),
          explore_articles_path, class:"nav-link text-dark" %>
      </li>

      <li class="dropdown-item">
        <%= link_to t("all articles"),
        articles_path, class:"nav-link text-dark" %>
      </li>

      
        <% if current_user.payed == true %>
          <li class="dropdown-item" >
            <span >
            <%= link_to t("members only"), members_only_articles_path, class:"nav-link text-dark", :style=>"background-color:salmon" %>
            </span>
          </li>  
        <% end %>
    </ul>
  </li>




 

app/views/partials/_languages.html.erb
  <% @languages.each do |language| %>
  <%= link_to t("#{language[0]} articles"), languages_path(language)  %>
  <% end %>

app/views/partials/_locals.html.erb
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-globe2 text-light lg" style="font-size: 1.5em;"></i>
    </a>
    <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
        <li class="dropdown-item">
          <%= link_to(locale: :ge) do %>
                    <img  width=30 class="c-icon ms-3 mt-2"  alt="geoflag" src="https://cdn.countryflags.com/thumbs/georgia/flag-400.png"> ქართული
                <% end %>
        </li>

        <li class="dropdown-item">
          <%= link_to(locale: :en) do %>
                    <img  width=30 height=21 class="c-icon ms-3 mt-2" alt="enflag" src="https://cdn.countryflags.com/thumbs/united-kingdom/flag-400.png"> english
                  <% end %>
        </li>
    </ul>
  </li>




  

app/views/partials/_navbar.html.erb
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-dark" style="position: fixed; top: 0; width: 100%; z-index: 9999;">
    <div  class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
        <li class="btn" style="color:white;">
            <%= link_to t("home"),
          root_path, class:"nav-link text-light" %>
        </li>
        
        <li class="dropbtn btn" style="color:white; ">
          <%= link_to t("categories"),
          categories_path, class:"nav-link text-white" %>
        </li>
            
        <li class="dropbtn btn" style="color:white;">
          <%if current_user.avatar.nil? %>
            <%= link_to image_tag("#{current_user.avatar}", :height => 40, :width=> 40, :alt => 'profile', :title => 'profile'), user_path(current_user), :class => 'nav-link text-light'%>
          <%else%>
            <%= link_to t("profile"), user_path(current_user), :class => 'nav-link text-light'%>
          <%end%>
          <%= render 'partials/articles'%>
        <li class="dropbtn btn" style="color:white;">     
          <% if policy(User).index? %>
            <%= link_to t("admin panel"),  admin_path(current_user), class:"nav-link text-light" %>
          <% end %>
        </li>  


       <% else %>
        <li>
            <%= link_to t("home"),
          root_path, class:"nav-link text-light" %>
        </li>

        <li >
        <%= link_to t("all articles"),
        articles_path, class:"nav-link text-light" %>
        </li>

        <li>
            <%= link_to t("categories"),
          categories_path, class:"nav-link text-white" %>
        </li>

        <li>
          <%= link_to t("explore"),
            explore_articles_path, class:"nav-link text-light" %>
        </li>
        
        <li>
            <%= link_to t("sign in"),
          new_user_session_path, class:"nav-link text-light" %>
        </li>

        <li>
            <%= link_to t("sign up"),
          new_user_registration_path, class:"nav-link text-light " %>
        </li> 
    <%end%>
      </ul>

      <ul class="navbar-nav ml-auto " >
        <li>
          <%= render 'partials/locals'%>
        </li>
        <% if user_signed_in? %>
          <li>
            <%= render 'partials/useroptions'%>
          </li>
          <li >
            <%= render 'layouts/notifications'%>
          </li>
        <%end%>
      </ul>
    </div>

  </nav>
</body>

app/views/partials/_useroptions.html.erb
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-person-circle" style="font-size: 1.5em; color: DarkSalmon;"></i>
    </a>
    <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
        <li class="dropdown-item">
          <%= link_to t("subscribe"),
            pricing_path, class:"nav-link text-danger" %>
        </li>
        <li class="dropdown-item">
         <%= link_to t("profile"), user_path(current_user), :class => 'nav-link text-dark'%>
        </li>
        <li class="dropdown-item">
          <%= link_to t("edit profile"),
            edit_user_registration_path, class:"nav-link text-dark" %>
        </li>
        <li class="dropdown-item">
          <%= link_to t("log out"),
          destroy_user_session_url, method: :delete, class:"nav-link text-dark font-weight-bold" %>
        </li>
      </ul>
  </li>