config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resources :categories
    resources :places
    devise_for :users, skip: :omniauth_callbacks, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }
    resources :categories

    root 'static_pages#index'
    devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end

    get 'articles/pdf/:id', to: 'articles#pdf', as: 'article_pdf'

    resources :articles do
      resources :comments
      collection do
        match 'search' => 'articles#search', via: [:get, :post], as: :search
      end
    end
    resources :users do
      resources :phones
    end
    resources :likes, only: %i[create destroy]
    resources :dislikes, only: %i[create destroy]
    get '/languages/:language', to: 'language#show', as: 'languages'
    get '/members_only/articles', to: 'members#articles', as: 'members_only_articles'
    get '/:id/locations', to: 'users#locations', as: 'user_locations'
    get '/explore', to: 'articles#explore', as: 'explore_articles'

    scope controller: :static do
      get :pricing
    end
    get '/success', to: 'purchase/checkouts#success'

    namespace :purchase do
      resources :checkouts
    end

    resources :subscriptions

    scope 'admin' do
      delete 'users/:id', to: 'admin#user_destroy', via: 'delete', as: 'admin_destroy_user'
      get ':id', to: 'admin#show', as: 'admin'
      get 'change_role/:id', to: 'admin#change_role', as: 'admin_change_role'
      patch 'make_admin/:id', to: 'admin#make_admin', via: 'patch', as: 'admin_make_admin'
      patch 'make_user/:id', to: 'admin#make_user', via: 'patch', as: 'admin_make_user'
      patch 'make_member/:id', to: 'admin#make_member', via: 'patch', as: 'admin_make_member'

      get 'article/approve/:id', to: 'admin#article_approve',  as: 'admin_article_approve'
      get 'article/disapprove/:id', to: 'admin#article_disapprove', as: 'admin_article_disapprove'
    end
  end
end

app/models/place.rb
# frozen_string_literal: true

class Place < ApplicationRecord
  belongs_to :user
  reverse_geocoded_by :latitude, :longitude, address: :name
  after_validation :reverse_geocode
  validates :latitude, presence: true
  validates :longitude, presence: true
end

app/controllers/places_controller.rb
# frozen_string_literal: true

class PlacesController < ApplicationController
  before_action :set_place, only: %i[show edit update destroy]

  # GET /places or /places.json
  def index
    @places = Place.all
  end

  # GET /places/1 or /places/1.json
  def show; end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit; end

  # POST /places or /places.json
  def create
    @place = Place.new(place_params)
    @place.user = current_user

    respond_to do |format|
      if @place.save
        format.html { redirect_to place_url(@place), notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1 or /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to place_url(@place), notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1 or /places/1.json
  def destroy
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_place
    @place = Place.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def place_params
    params.require(:place).permit(:name, :latitude, :longitude)
  end
end

app/helpers/places_helper.rb
# frozen_string_literal: true

module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_with model: place, local: true, data: {
                                            controller: :maps,
                                            action: "google-maps-callback@window->maps#initializeMap"
                                          } do |form| %>

  <% if place.errors.any? %>
    <div style="color: red">
      <h2><%= I18n.locale == :en ? pluralize(place.errors.count, "error") : "#{place.errors.count} შეცდომის გამო" %> <%= t("prohibited this location from being saved")%>:</h2>
    <ul>
    <% place.errors.each do |error| %>
      <li><%= t(error.full_message) %></li>
    <% end %>
    </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label t(:search) %>
    <%= form.search_field :search, name: nil, class: 'form-control', data: { target: "maps.field", action: "keydown->maps#preventSubmit" } %>
  </div>

  <div class="field">
    <%= form.label t(:latitude) %>
    <%= form.text_field :latitude, class: 'form-control', data: { target: "maps.latitude" } %>
  </div>

  <div class="field">
    <%= form.label t(:longitude) %>
    <%= form.text_field :longitude, class: 'form-control', data: { target: "maps.longitude" } %>
  </div>

  <%= content_tag :div, nil, data: { target: "maps.map" }, class: 'map'%>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/places/_place.html.erb
<div id="<%= dom_id place %>">
  <p>
    <strong><%= t('Name')%>:</strong>
    <%= place.name %>
  </p>


  <p>
    <strong><%= t('Latitude')%>:</strong>
    <%= place.latitude %>
  </p>

  <p>
    <strong><%= t('Longitude')%>:</strong>
    <%= place.longitude %>
  </p>
<p>
<%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=15&size=400x300&center=#{place.latitude},#{place.longitude}&key=#{Rails.application.credentials.dig(:MAPS_API_KEY)}", alt: "Map" %>

</p>

</div>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render "form", place: @place %>

<br>

<div>
  <%= link_to t("Show this place"), @place, class: "btn btn-primary" %> 
</div>

app/views/places/index.html.erb
<div id="places">
  <% @places.each do |place| %>
    <%= render place %>
    <p>
      <%= link_to t("Show this place"), place , class: "btn btn-primary"%>
    </p>
  <% end %>
</div>

<%= link_to t("New place"), new_place_path, class: "btn btn-primary" %>

app/views/places/new.html.erb
<h1><%= t("add location here")%></h1>

<%= render "form", place: @place %>

<br>

app/views/places/show.html.erb
<%= render @place %>

<div>
  <%= link_to t("Edit this place"), edit_place_path(@place), class: "btn btn-outline-danger" %> 
  <p> <%= button_to t("Destroy this place"), @place, method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}} , class: "btn btn-outline-danger"%> </p>
</div>